create database `checkers`;
use checkers;
create table 02_tiles ( board CHAR(32), next_board CHAR(32), weight DECIMAL(3,2), PRIMARY KEY(board) );
create table 03_tiles ( board CHAR(32), next_board CHAR(32), weight DECIMAL(3,2), PRIMARY KEY(board) );
create table 04_tiles ( board CHAR(32), next_board CHAR(32), weight DECIMAL(3,2), PRIMARY KEY(board) );
create table 05_tiles ( board CHAR(32), next_board CHAR(32), weight DECIMAL(3,2), PRIMARY KEY(board) );
create table 06_tiles ( board CHAR(32), next_board CHAR(32), weight DECIMAL(3,2), PRIMARY KEY(board) );
create table 07_tiles ( board CHAR(32), next_board CHAR(32), weight DECIMAL(3,2), PRIMARY KEY(board) );
create table 08_tiles ( board CHAR(32), next_board CHAR(32), weight DECIMAL(3,2), PRIMARY KEY(board) );
create table 09_tiles ( board CHAR(32), next_board CHAR(32), weight DECIMAL(3,2), PRIMARY KEY(board) );
create table 10_tiles ( board CHAR(32), next_board CHAR(32), weight DECIMAL(3,2), PRIMARY KEY(board) );
